# Generated by Django 3.2.8 on 2021-12-13 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(help_text='Артикул', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Бренд', max_length=50, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Категория товара', max_length=20, verbose_name='Категория товара')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(blank=True, help_text='Город', max_length=20, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Цвет', max_length=20, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Number_Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_office', models.CharField(blank=True, help_text='Номер отделения', max_length=10, verbose_name='Номер отделения')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(help_text='Люди.Для кого товар.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Postoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(blank=True, help_text='Название перевозчика', max_length=100, verbose_name='Название перевозчика')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Наименование', max_length=50, verbose_name='Наименование')),
                ('price', models.CharField(blank=True, help_text='Цена', max_length=10, verbose_name='Цена')),
                ('pic', models.ImageField(blank=True, db_index=True, upload_to='static/photo/%Y/%m/%d/', verbose_name='Фото')),
                ('components', models.CharField(blank=True, help_text='Состав изделия', max_length=250, verbose_name='Состав изделия')),
                ('description', models.TextField(blank=True, help_text='Описание товара', verbose_name='Описание товара')),
                ('add_product', models.CharField(blank=True, help_text='Количество товара', max_length=20, null=True, verbose_name='Добавить количество товара')),
                ('art', models.ForeignKey(blank=True, help_text='Артикул', on_delete=django.db.models.deletion.PROTECT, to='catalog.art', verbose_name='Артикул')),
                ('brand', models.ForeignKey(help_text='Бренд', on_delete=django.db.models.deletion.PROTECT, to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(help_text='Категория товара', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория товара')),
                ('color', models.ManyToManyField(help_text='Цвет', to='catalog.Color', verbose_name='Цвет')),
                ('people', models.ManyToManyField(help_text='Люди. Для кого товар', to='catalog.People', verbose_name='Кому товар предназначен')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text='Наименование сезона', max_length=20, verbose_name='Наименование сезона')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Размер', max_length=20, verbose_name='Размер')),
            ],
        ),
        migrations.CreateModel(
            name='Socks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SocksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sockslist', models.CharField(help_text='Виды носков', max_length=20, verbose_name='Виды носков')),
            ],
        ),
        migrations.CreateModel(
            name='WearsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wearslist', models.CharField(help_text='Виды одежды', max_length=20, verbose_name='Виды одежды')),
            ],
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            bases=('catalog.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ManyToManyField(help_text='Наименование сезона', to='catalog.Season', verbose_name='Наименование сезона'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(help_text='Размер изделия', to='catalog.Size', verbose_name='Размер изделия'),
        ),
        migrations.AddField(
            model_name='product',
            name='socklist',
            field=models.ForeignKey(blank=True, help_text='Вид носков', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.sockslist', verbose_name='Вид носков'),
        ),
        migrations.AddField(
            model_name='product',
            name='wearlist',
            field=models.ForeignKey(blank=True, help_text='Вид одежды', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.wearslist', verbose_name='Вид одежды'),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(blank=True, help_text='Фамилия', max_length=20, verbose_name='Фамилия')),
                ('firstname', models.CharField(blank=True, help_text='Имя', max_length=20, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона', max_length=14, verbose_name='Номер телефона')),
                ('deliveryaddress', models.CharField(blank=True, help_text='Улица, проспект, переулок', max_length=50, verbose_name='Улица, проспект, переулок')),
                ('number', models.CharField(blank=True, help_text='Номер дома', max_length=5, verbose_name='Номер дома')),
                ('apt', models.CharField(blank=True, help_text='Номер квартиры (если есть)', max_length=5, verbose_name='Номер квартиры (если есть)')),
                ('index', models.CharField(blank=True, help_text='Почтовый индекс', max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('desc', models.TextField(blank=True, help_text='Комментарии к заказу', verbose_name='Комментарии к заказу')),
                ('cities', models.ForeignKey(blank=True, help_text='Город', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cities', verbose_name='Город')),
                ('customer', models.ForeignKey(blank=True, help_text='Название организации', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.customer', verbose_name='Название организации')),
                ('numberoffice', models.ForeignKey(blank=True, help_text='Номер отделения', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.number_office', verbose_name='Номер отделения')),
                ('postoffice', models.ForeignKey(blank=True, help_text='Название перевозчика', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.postoffice', verbose_name='Название перевозчика')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.CharField(blank=True, help_text='Цена', max_length=10, verbose_name='Цена')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.CharField(blank=True, help_text='Цена', max_length=10, verbose_name='Цена')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.customer', verbose_name='Владелец')),
                ('products', models.ManyToManyField(blank=True, related_name='related_cart', to='catalog.CartProduct')),
            ],
        ),
    ]
