# Generated by Django 3.2.8 on 2022-01-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220120_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон'),
        ),
    ]
